language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev
 
before_install:
  - cd $TRAVIS_BUILD_DIR/python
install:
  - python setup.py install  
# command to run tests
script: 
  - echo $(pwd)
  - echo "`pwd`"
  - echo $(pwd)
  - cd $TRAVIS_BUILD_DIR/python/tests/keyczar_tests && python alltests.py 
